PUT http://localhost:8080/orderStatus/1
Content-Type: application/json

{"orderId": 1, "status": "Gotovo"}

###
GET http://localhost:8080/order/1
Accept: application/json

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": 1,
  "orderId": 1,
  "userId": 1,
  "itemId": 1,
  "menuId": 1,
  "count": 2
}

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": 2,
  "orderId": 1,
  "userId": 1,
  "itemId": 2,
  "menuId": 1,
  "count": 1
}

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": 3,
  "orderId": 2,
  "userId": 2,
  "itemId": 1,
  "menuId": 1,
  "count": 5
}

###

PUT http://localhost:8080/order/2
Content-Type: application/json

{
  "id": 3,
  "orderId": 2,
  "userId": 2,
  "itemId": 1,
  "menuId": 1,
  "count": 5
}

###
GET http://localhost:8080/ordersWith/Accepted
Content-Type: application/json


###